FROM payara/server-full:5.2022.1-jdk11

RUN echo 'create-jdbc-connection-pool \
		    --datasourceclassname com.mysql.cj.jdbc.MysqlDataSource \
			--restype javax.sql.DataSource \
			--property databaseName=users_management:serverName=RemoteMySQLDatabase:portNumber=3306:AllowPublicKeyRetrieval=true:UseSSL=false:Password=root:User=root:URL=jdbc\:mysql\://database\:3306/users_management users_management_datapool\n\r \
          create-jdbc-resource \
			--connectionpoolid users_management_datapool jdbc/users_management_jta' \
 > $POSTBOOT_COMMANDS

COPY build/libs/usermanagementservice.war $DEPLOY_DIR