version: "3.8"

services:

  database:
    image: mysql
    mem_limit: 700m
    hostname: database
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: users_management
      MYSQL_ROOT_PASSWORD: root
    networks:
      - javabackend1

  usersmanagementservice:
    image: dockersentinel/user-management-service
    mem_limit: 700m
    depends_on:
      - database
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - "8080:8080"
      - "4848:4848"
    hostname: usersmanagementservice
    networks:
      - javabackend1

networks:
  javabackend1: